import settings from "./config";
import renderBeaconBeam from "../BeaconBeam";

import "./features/maskTimers"
import "./features/maskNotifications"
import "./features/arrowStackLocations"

import "./features/chatPrefix"
import "./features/TermWaypoints"
import "./features/highlightStarMobs"
import "./features/bloodHelper"
import "./features/partyCommands"
import "./features/etherwarpOverlay"
import "./features/highlightKeys"
import "./features/boxNecron"
import "./features/ragAxe"
import "./firstInstall"
import "./features/autoRefill"
import "./features/announceLeap"
import "./features/voidgloomDIsplay"
import "./features/feroOverlay"
import "./features/cataStats"
import "./features/f7Routes"
import "./features/f7splits"
import "./features/flares"
import "./features/vanqShare"
import "./features/mining"
import "./features/blockhighlight"